version: '2'
services:
  hasheous-server:
    container_name: hasheous-server
    build:
      context: ./
    restart: unless-stopped
    networks:
      - hasheous
    depends_on:
      - hsdb
    ports:
      - 7157:80
    volumes:
      - hs:/root/.hasheous-server
    environment:
      - dbhost=hsdb
      - dbuser=root
      - dbpass=hasheous
      - igdbclientid=<clientid>
      - igdbclientsecret=<clientsecret>
      - igdbusedumps=false
  hsdb:
    container_name: hsdb
    image: mariadb
    restart: unless-stopped
    networks:
      - hasheous
    volumes:
      - hsdb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=hasheous
      - MARIADB_USER=hasheous
      - MARIADB_PASSWORD=hasheous
  valkey:
    hostname: valkey
    image: valkey/valkey:latest
    restart: unless-stopped
    networks:
      - hasheous
    volumes:
      - hs:/root/.valkey
    ports:
      - 6379:6379
    environment:
      - VALKEY_EXTRA_FLAGS=--save 60 1 --loglevel warning
networks:
  hasheous:
    driver: bridge
volumes:
  hs:
  hsdb:
