services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    stdin_open: true
    environment:
      - TZ=Australia/Sydney
      - dbhost=mariadb
      - dbuser=root
      - dbpass=hasheous
      - igdbclientid=${IGDBCLIENTID}
      - igdbclientsecret=${IGDBCLIENTSECRET}
      - igdbusedumps=${IGDBUSEDUMPS}
      - redisenabled=true
      - redishost=valkey
      - redisport=6379
      - googleclientid=${GOOGLECLIENTID}
      - googleclientsecret=${GOOGLECLIENTSECRET}
      - microsoftclientid=${MICROSOFTCLIENTID}
      - microsoftclientsecret=${MICROSOFTCLIENTSECRET}
  mariadb:
    hostname: mariadb
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MARIADB_ROOT_PASSWORD=hasheous
      - MARIADB_DATABASE=hasheous
      - MARIADB_USER=root
      - MARIADB_PASSWORD=hasheous
  valkey:
    hostname: valkey
    image: valkey/valkey:latest
    ports:
      - 6379:6379
    environment:
      - VALKEY_EXTRA_FLAGS=--save 60 1 --loglevel warning
