ALTER TABLE `Signatures_Games`
ADD COLUMN `MetadataSource` INT DEFAULT 0,
ADD COLUMN `SourceId` BIGINT DEFAULT 0;

ALTER TABLE `Signatures_Roms`
ADD COLUMN `Countries` varchar(255) NOT NULL DEFAULT '{}',
ADD COLUMN `Languages` varchar(255) NOT NULL DEFAULT '{}',
ADD COLUMN `DateAdded` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `DateUpdated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;