ALTER TABLE `Signatures_Sources`
ADD COLUMN `processed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `SourceType`;

ALTER TABLE `Signatures_Games`
ADD COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Signatures_Roms`
RENAME COLUMN `DateAdded` TO `created_at`,
RENAME COLUMN `DateUpdated` TO `updated_at`;

ALTER TABLE `Signatures_Roms`
CHANGE COLUMN `created_at` `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
CHANGE COLUMN `updated_at` `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;