name: Build Release Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion
      - name: Set tag to version  
        run: dotnet TagToVersion -t ${{ github.ref }}
      - name: Sign in to Nuget
        run: dotnet nuget add source --username michael-j-green --password ${{ secrets.NUGETKEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/gaseous-project/index.json"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Hasheous Web Server image
        uses: docker/build-push-action@v6
        with:
          context: ./hasheous
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gaseousgames/hasheous:latest
            gaseousgames/hasheous:${{ github.ref_name}}
            ghcr.io/gaseous-project/hasheous:latest
            ghcr.io/gaseous-project/hasheous:${{ github.ref_name}}
      - name: Build and push Hasheous Orchestration Server image
        uses: docker/build-push-action@v6
        with:
          context: ./service-ochestrator
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gaseousgames/hasheous-orchestrator:latest
            gaseousgames/hasheous-orchestrator:${{ github.ref_name}}
            ghcr.io/gaseous-project/hasheous-orchestrator:latest
            ghcr.io/gaseous-project/hasheous-orchestrator:${{ github.ref_name}}
