name: Copilot Instructions Guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  guard:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changes that should update copilot-instructions.md
        shell: bash
        run: |
          set -eo pipefail
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.sha }}"
          echo "Base: $BASE_SHA"
          echo "Head: $HEAD_SHA"

          CHANGED=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" | tr -d '\r')
          echo "Changed files:"
          echo "$CHANGED" | sed 's/^/ - /'

          # Files whose changes imply the instructions likely need updates
          NEEDS_DOC_CHANGE_REGEX='^(hasheous/(Program\.cs|Controllers/)|service-orchestrator/Program\.cs|hasheous-lib/Classes/(Config\.cs|Database\.cs|Redis\.cs|SignatureIngestors/)|hasheous-lib/Controllers/HealthcheckController\.cs|hasheous/Properties/launchSettings\.json|service-orchestrator/Properties/launchSettings\.json|hasheous/docker/|service-orchestrator/docker/|docker-compose-build\.yml|hasheous-lib/Schema/|README\.MD)'

          INSTRUCTIONS_PATH='.github/copilot-instructions.md'
          NEEDS_UPDATE=$(echo "$CHANGED" | grep -E "$NEEDS_DOC_CHANGE_REGEX" || true)
          UPDATED_DOC=$(echo "$CHANGED" | grep -E "^${INSTRUCTIONS_PATH}$" || true)

          if [ -n "$NEEDS_UPDATE" ] && [ -z "$UPDATED_DOC" ]; then
            echo "::error::Detected changes to architecture/config files without updating ${INSTRUCTIONS_PATH}. Please review and update it or add an exception if not needed."
            echo "Files triggering this check:"
            echo "$NEEDS_UPDATE" | sed 's/^/ - /'
            if [ -f .github/scripts/copilot-instructions-help.sh ]; then
              echo "$NEEDS_UPDATE" | bash .github/scripts/copilot-instructions-help.sh "$INSTRUCTIONS_PATH"
            fi
            exit 1
          else
            echo "No copilot-instructions update required."
          fi
